# Default values for devops-task-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count.
replicaCount: 1

# This sets the container image.
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

# Secrets for pulling an image from a private repository.
imagePullSecrets: []

# Override the chart name.
nameOverride: ""
fullnameOverride: ""

# Service account configuration.
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels.
podAnnotations: {}
podLabels: {}

# Pod security context.
podSecurityContext: {}
  # fsGroup: 2000


# =========================================================
# FRONTEND
# =========================================================

frontend:
  image: devops-task-manager-frontend:v9
  replicaCount: 1
  servicePort: 80


# =========================================================
# FLASK BACKEND
# =========================================================

flask:
  image: devops-task-manager-backend:v3
  replicaCount: 1
  servicePort: 5000
  dbHost: postgres-service


# =========================================================
# POSTGRESQL DATABASE
# =========================================================

postgres:
  image: postgres:16
  dbName: taskmanager
  dbUser: devops
  dbPassword: REMOVED_PASSWORD
  servicePort: 5432


# =========================================================
# INGRESS
# =========================================================

ingress:
  enabled: true
  host: taskmanager.local


# =========================================================
# PERSISTENT STORAGE
# =========================================================

persistence:
  size: 1Gi
