apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment

spec:
  replicas: {{ .Values.flask.replicaCount }}

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      containers:
        - name: flask
          image: {{ .Values.flask.image }}
          imagePullPolicy: Never

          ports:
            - containerPort: {{ .Values.flask.servicePort }}

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
